### ISSUE TITLE
New Class Beast Channeler Icons

### ISSUE THREAD

**Issue by FlintSparker** [TheRealDjmr/BG3ImprovedUI#100]
Hello,

I am a new Modder working on creating my own Character Class. I was able to get some Icons for the class and subclasses but couldn't get them to show up in game and was directed by someone that has been helping me that I need to make a post here for it. The Icons are currently located in BeastChanneler/Public/Game/Gui/Assests/BeastChanneler/ClassIcons in the attached .pak. If this is not how I should be going about getting this implemented please let me know and also please let me know if there is another way I should be going about this.

Thanks,
Flint
[BeastChanneler.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/12696204/BeastChanneler.zip)

**Comment by TheRealDjmr** [comment]
I have added a guide for adding icons on the bg3 wiki - https://bg3.wiki/wiki/Modding_Class_Icons
