### ISSUE TITLE
Magic Mirror in new patch will not work with Improved UI

### ISSUE THREAD

**Issue by ACMECoyote** [TheRealDjmr/BG3ImprovedUI#102]
The Improved UI mod is keeping players post-patch from using the new Magic Mirror feature. For 90% of players, the Magic Mirror works after disabling ImprovedUI.

**Comment by TheRealDjmr** [comment]
Updated for patch 3 - https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.9
