### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by CyberTech21** [TheRealDjmr/BG3ImprovedUI#11]
![Inventory bug](https://user-images.githubusercontent.com/11529413/131754285-982dc110-5b3d-4cc8-ad9d-dcfeb2f3250f.png)

Since Hotfix #14 there seems to be a bug with this mod that doesn't show the inventory correctly and when trying to move or take things out of the inventory it won't do anything.

Was wondering if there is a fix in process because I love this mod when playing Baldur's Gate 3.

(Did test my other mods that I use and this was the only one that seems to bring up the inventory issue.)

**Comment by TheRealDjmr** [comment]
Hi CyberTech21, there's a new version of the datatemplates.xml in the latest hotfix causing this issue. I'm just taking a look at what's changed now.

**Comment by TheRealDjmr** [comment]
Hi CyberTech21, I've created a new version that fixes this issue, you can now see the tiles between items that were added in the latest hotfix and can drag items around

**Comment by CyberTech21** [comment]
Thank you so much!!! This is the best news to come home to!!! 

Your mod helps my Baldur's Gate 3 experience so much better!!  I hope for good things in your future!!
