### ISSUE TITLE
Not really an issue but I'm just throwing it out there since it's probably a UI thing

### ISSUE THREAD

**Issue by violencepierre** [TheRealDjmr/BG3ImprovedUI#114]
the pop up for Wild Magic Surge. Would you know how the game pulls that up? I'd love to make my own, with my own custom text and custom icon. This is the handle UUID: h494c3752g77e8g407cgb42eg19033f819d1e, at least for the text that says "Wild Magic Surge!"

**Comment by TheRealDjmr** [comment]
Looking at your post on BG3 modding you'd want to make your own version of Wild Magic Surge. That pop-up will always appear when "Wild Magic Surge" is triggered.
