### ISSUE TITLE
Bug: 2 voice selection drop downs

### ISSUE THREAD

**Issue by samophlange** [TheRealDjmr/BG3ImprovedUI#130]
The voice selection at character creation is duplicated with 3.12. Only 1 was visible with 3.11. 

![double voice](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/92848788/fcf5a25f-bbf1-44cf-be9c-901f011762ba)

![bg3mm](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/92848788/5f5f51bb-cb78-48f8-a03c-0f4e27c8f4a3)

The screenshot on the release page shows the voice selector being doubled as well 
[https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.12](url)

With ImprovedUI removed the issue isn’t present.

Unrelated, also am still getting the reset tutorials popup.

**Comment by TheRealDjmr** [comment]
Updated release - https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.12

for reset tutorials popup check if you have any loose statemachine.xaml files

**Comment by samophlange** [comment]
negative on the loose statemachine.xaml

![Untitled](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/92848788/c3afe0b9-78d3-4933-a0df-aa0160e476c1)
