### ISSUE TITLE
Importing action resources dynamically

### ISSUE THREAD

**Issue by TheRealDjmr** [TheRealDjmr/BG3ImprovedUI#145]
Class icons can integrate with ImprovedUI, without requiring an entry - https://bg3.wiki/wiki/Guide:Modding_Class_Icons

Before getting an action resource icon guide, I want to import action resources dynamically (as much as I can)

This might not be possible for every icon and every section, but it would at least provide an easier method of integrating action resources.

**Comment by TheRealDjmr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dynamic Action Resource support + Adding Action Resources to ImprovedUI guide](https://trello.com/c/pjqZdMBV/36-dynamic-action-resource-support-adding-action-resources-to-improvedui-guide)

**Comment by juliandwillett** [comment]
Thanks for this, I am actually trying to do this right now. Would it be possible to share that guide and make it public?

**Comment by TheRealDjmr** [comment]
> Thanks for this, I am actually trying to do this right now. Would it be possible to share that guide and make it public?

@juliandwillett hey, Trello is just our way of managing the to-do list, rather than something already done. I'm planning to do a Github guide this weekend

As a starting point, I'd always recommend looking at a supported mod (like Artificer) to see how it's done

There is also this guide by Kalivos - https://docs.google.com/document/d/18JMDanoAUNg0uwU2GhA0pPekvGSuqIDJNDMHUOHZIT8/edit#heading=h.4ga291m924cz

Feel free to reach out over Discord too if you're stuck

**Comment by juliandwillett** [comment]
Will do, thanks for the help! Looking forward to seeing that action resource icon guide when you get a chance to put it together. I'll look at Artificer again once I get to the action resource icon stage (finished debugging the class icon last night).

**Comment by juliandwillett** [comment]
I attempted to implement the custom action resource icons, following that tutorial and the example used by Artificer, both of which sadly did not work. While I'll look over another couple mods tomorrow, ever get a chance to write up the guide on dynamically loading the action resource icons?

**Comment by nicholaiTukanov** [comment]
Has anyone experienced #356 when adding in custom icons?

**Comment by TheRealDjmr** [comment]
This has been implemented in patch 7
