### ISSUE TITLE
Hair color options overflow when selected from the Facial Hair tab

### ISSUE THREAD

**Issue by logical-fallazee** [TheRealDjmr/BG3ImprovedUI#170]
![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/83232936/3163bed9-434f-43e7-81af-9e11c4a41e67)

Kindly reported by Astralities.

> It happens when you open the color selection from the facial hair tab while having modded hair colors installed that increase the number of colors so much that it bleeds out of the box. 
> The actual main panel looks fine, [and you don't see the issue when selecting hair color from the hair tab], just the popup when you open the color options panel from the facial hair panel.

Confirmed with some initial testing that this:
* occurs with or without IUI (no visible difference-- better or worse-- either way),
* only occurs when a user has installed a certain number of modded hair color options (surpassing "critical mass" of what the panel expected to contain),
* does not occur in the base game (because the vanilla game does not include enough hair color options for critical mass to even come close to being reached),
* only affects the hair color selection panel from within the Facial Hair tab. The main Hair tab's color selection panel is not affected.

The issue includes:
* color options exceeding the bounds of the panel,
* scrolling is not possible within the panel (what options you see is what you get; excess options are cut off),
* the last row of visible color options is not clickable. (The confirm button works, and selecting an option above the last row also works as expected.)

**Comment by TheRealDjmr** [comment]
We'd want to update the template for all colour selections here if possible

It might be possible to add a scroll bar to the colour options once they get too large (like the other scroll bars added with ImprovedUI)

**Comment by TheRealDjmr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hair colours overflow](https://trello.com/c/ZY4j9Gse/33-hair-colours-overflow)

**Comment by TheRealDjmr** [comment]
Fixed in #203
