### ISSUE TITLE
Double spells in char creation

### ISSUE THREAD

**Issue by tarkan9801** [TheRealDjmr/BG3ImprovedUI#20]
Hi i got double spells in char creation as sorcerer.

**Comment by TheRealDjmr** [comment]
Hi Tarkan9801,

Are you using the latest version of this mod? Can you elaborate more on what is happening or provide screenshots?

**Comment by tarkan9801** [comment]
Hi I found that its doing another mod.

ut 16. 11. 2021 o 13:46 TheRealDjmr ***@***.***> napísal(a):
