### ISSUE TITLE
Subclass mod unable to select skills during progression levelup

### ISSUE THREAD

**Issue by Sumradagnoth** [TheRealDjmr/BG3ImprovedUI#219]
I am finding that during the levelup screen, when a subclass Progression has a SelectSkills Selector, the parent Class will light up red like you should go back and select something, but the skill selection does not appear.  Testing with only the mod and Improved UI loaded.

I did confirm that the SelectSkills points to the right SkillsList

**Comment by TheRealDjmr** [comment]
If this is a custom class, then it's currently requiring SelectSkillsExpertise. I've previously discussed it but putting it here - "we should be able to make it visible if we have skills OR expertise"

**Comment by TheRealDjmr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Select Skills without expertise - classes](https://trello.com/c/Wvk3ty8h/66-select-skills-without-expertise-classes)

**Comment by Sumradagnoth** [comment]
Also… it’s a custom subclass using the fighter parent class

**Comment by TheRealDjmr** [comment]
This is included in the latest version of the mod
