### ISSUE TITLE
can't find .pak file

### ISSUE THREAD

**Issue by NixKyrul** [TheRealDjmr/BG3ImprovedUI#28]
I'm truly sorry but I'm not tech savvy so I'm having issues doing what is probably considered basic stuff I have no idea how to use lslib if anyone can just tell me the steps necessary to use it would be awesome.
(i tried looking for tutorials somewhere but i can't find anything)

**Comment by Kickball** [comment]
You can find the `.pak` file in the `.zip` file under the **Assets** heading of each release, which can be found here: https://github.com/TheRealDjmr/BG3ImprovedUI/releases (e.g.  [BG3ImprovedUI-2.15.1.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/releases/download/2.15.1/BG3ImprovedUI-2.15.1.zip) which is the latest at the time of this comment).
