### ISSUE TITLE
Latest patch 

### ISSUE THREAD

**Issue by dlykely** [TheRealDjmr/BG3ImprovedUI#290]
We seem to have issue with improved ui and the latest patch update. Several sliders in character creation go past the frame. 
![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/160250270/1bf4c86c-9b1d-4396-9731-35b8e1710657)

**Comment by TheRealDjmr** [comment]
Yep an update will be required, working on it

**Comment by TheRealDjmr** [comment]
![20240216200927_1](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/80291281/f4ad68e4-a5cd-4e35-b5d7-948c44c869de)

**Comment by TheRealDjmr** [comment]
Fixed in https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.18beta

**Comment by dlykely** [comment]
> Fixed in https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.18beta

Thank you so much! <3
