### ISSUE TITLE
>2 Racial Passives Change Order in Side Tabs in CC

### ISSUE THREAD

**Issue by logical-fallazee** [TheRealDjmr/BG3ImprovedUI#331]
Mod author reported that, during testing, their modded race's passive switched from position 1 of 3 to position 3 of 3 when they selected any class in character creation. The order of the passives returned to 1 of 3 if the race was re-selected. (They also indicated that if they reordered the passives in the progression to have the [pictured] origin passives listed first and their racial passive third, then this same swapping behavior occurred [3 of 3 -> 1 of 3].)

![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/83232936/79afea5b-6c35-4d08-995e-6dd23b21c0a2)

![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/83232936/e2a5a1c7-6a0c-4509-b7ff-182cacb4d3af)

This behavior has _not_ been observed when there are only 2 racial passives during character creation.

**Comment by TheRealDjmr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Subtab order changing](https://trello.com/c/o81Mnepn/180-subtab-order-changing)

**Comment by TheRealDjmr** [comment]
This is an unsorted list that cannot be sorted in the UI
