### ISSUE TITLE
Feature request: remove third-party mod warnings

### ISSUE THREAD

**Issue by AtilioA** [TheRealDjmr/BG3ImprovedUI#368]
Patch 7 released today and kept the use of the warning symbol (yellow triangle with an exclamation mark) to label third-party mods, which could lead to confusion among mod users. This symbol is typically associated with something being wrong or potentially harmful, which might cause unnecessary concern.

Users unfamiliar with modding may feel nervous about using mods labeled in this way, and it might discourage them from experimenting with third-party content, which encompasses all Script Extender mods.
Feedback from non-modders about their interpretation of the symbol includes:

> - _steam cloud save isn't synced_
> - _the mod is broken_ (x3)
> - _the mod is out of date_
> - _you are missing mods on that save_

This confusion is compounded by the fact that third-party mods are labeled in four places: in the main menu, "continue" and "new game" buttons, "load game" menu, and the in-game mod manager.

**Since IUI is the largest UI mod, and is concerned with UI changes, I suggest that it removes all such warnings.**

Examples:
<img width="530" alt="warning" src="https://github.com/user-attachments/assets/4825b73c-972c-4fd3-ae8f-86f638922743">
![image](https://github.com/user-attachments/assets/7a1b9351-d212-4efc-a935-3c0dc26256a3)

**Comment by TheRealDjmr** [comment]
This has been fed back to Larian. ImpUI shouldn't change the official modding process - especially when it's still being worked on
