### ISSUE TITLE
Death Soul Subclass Icon Not Appearing in Patch 7

### ISSUE THREAD

**Issue by Zeysir** [TheRealDjmr/BG3ImprovedUI#370]
As the title says. Weirdly enough, I tried loading Patch 7 of Improved UI and the Improved Assets Patch 6 together (no Improved UI Patch 6) and the icon came back.

**Comment by Zeysir** [comment]
All right, for now I'll just recommend that users load my mod with the Patch 6 assets then.

**Comment by TheRealDjmr** [comment]
Class icons are officially supported under a different folder path - https://mod.io/g/baldursgate3/r/adding-new-classes#heading-12
