### ISSUE TITLE
Feature Request: Allow to add feat selection screen to character creation for races

### ISSUE THREAD

**Issue by TyrasNistru** [TheRealDjmr/BG3ImprovedUI#372]
It would be nice to be able to add feats like we can spells and passives to subraces! The AllowImprovement flag doesn't seem to work for them as they do for classes

**Comment by TyrasNistru** [comment]
> > It would be nice to be able to add feats like we can spells and passives to subraces! The AllowImprovement flag doesn't seem to work for them as they do for classes
> 
> This is a limitation we are currently unable to work around. I am hopeful that the developers will provide us a way to do so in the future.

I see... thanks for the help!

**Comment by TyrasNistru** [comment]
Sorry to bother again, but, my curiosity as a dev is getting to me.

What is the limitation?

**Comment by TheRealDjmr** [comment]
This is something I've investigated before since early access and also full release.

There isn't any feat UI data available to show during level 1. The game would need to be patched/changed to support feats in character creation.
