### ISSUE TITLE
Request: Remove Minimap Option

### ISSUE THREAD

**Issue by Wawsax** [TheRealDjmr/BG3ImprovedUI#38]
[This mod on Nexus](https://www.nexusmods.com/baldursgate3/mods/621) seems to work right now in conjunction with yours. Given the potential incompatibilities/conflicts between mods, though, it would be nice if you incorporated the option to disable the minimap. Damn thing is gigantic and seems entirely useless in this game.

**Comment by TheRealDjmr** [comment]
Hi Wawsax,

I've added 2 optional files - 1 with a smaller Minimap, and 1 with no Minimap - https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.3.1
