### ISSUE TITLE
Red Minimap Overlay has vanilla scale.

### ISSUE THREAD

**Issue by koticR** [TheRealDjmr/BG3ImprovedUI#42]
Pictures say more than a thousand words, so here you go. :)

![minimap_issue](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/2699136/56c445fb-3c43-4eda-b867-3d91122633b9)

**Comment by TheRealDjmr** [comment]
Made new version of smallerminimap that resizes this
[ImprovedUI Smallerminimap.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/12423193/ImprovedUI.Smallerminimap.zip)
