### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Xetaxheb** [TheRealDjmr/BG3ImprovedUI#47]
I'm currently (unfortunately) maintaining

https://www.nexusmods.com/baldursgate3/mods/1448

as the Patch 1 "mod fixer"

Someone was complaining, what I assume to be _baselessly_, about a conflict between our /public/game/gui/StateMachine.xaml files somehow breaking showallitems toggling. I use ImpUI3.4.1+showallitems with no issues on patch 1 and I couldn't reproduce it.
They said that "just having both mods add the files causes conflict" which I feel is obviously untrue (assuming they're functionally identical) but separately:

I want to attempt to keep parity with yours but is there a reason (besides outdated from patch 1) yours is missing 
`L367~ <ls:PreloadState Name="PinnedTooltips"/>
`inside of 
` L352 <ls:State Name = "CharacterFullRespec" HideStatesBelow = "True" DisableStatesBelow = "True" Layout = "Player" Owner = "Player" ForceSplitscreen="True">
`
(not to be confused with _<ls:AddSubstate Name="PinnedTooltips"/>_ )

and 

is there a reason you leave in 
`L27 <ls:State.Events>`
`L35</ls:State.Events>`
inside 
`L26 <ls:State Name = "SystemRoot" Layout = "Common" Owner = "All">`

? Just asking so I don't accidentally break anything of yours. My main file removes L27/L35 and my optional file ("improvedui compat", see bug thread for why it came about) leaves it intact; both files leave L367 intact.

Also as someone who seems invested enough in continuing modding BG3 with something that will be widely used and integral, LMK if you would like edit access to the mod page ^^

**Comment by TheRealDjmr** [comment]
The mod you linked has been taken down for moderation.

I haven't uploaded a patch 1 version yet. It dropped when I was in work, so it's not updated yet.

Welcome to BG3 UI modding, any xaml files that are changed in different mods cause conflicts. I'd rather ImprovedUI is added as a required mod
