### ISSUE TITLE
Multiplayer issue

### ISSUE THREAD

**Issue by Megaflamewolf** [TheRealDjmr/BG3ImprovedUI#50]
Whenever my freind joins and we have this mod enabled via vortex it kicks him back to the main menu a few seconds after he joins

**Comment by TheRealDjmr** [comment]
You would both need the same mods installed. This has always been the case during early access.

A quick google brings up this:

"Mods are not supported by Larian and must come from third-party carriers. If you choose to install mods in Baldur's Gate 3, unlike many other games, Multiplayer still functions.

It is highly recommended, however, to have all members of the party installed with the same mod list. Deviating from this is known to cause catastrophic or game-breaking issues that can range from blocking inventory lists to corrupting saves to hard-closing the program."

**Comment by Megaflamewolf** [comment]
We had the same exact mods in fact we only had this mod enabled so it's not that it's the mod
