### ISSUE TITLE
Patch 2 released, dice rolls not working. 

### ISSUE THREAD

**Issue by midnastorm** [TheRealDjmr/BG3ImprovedUI#55]
Dice rolls are broken, during non cutscenes a quicksave and quick load seem tobe able to fix it, but during cutscenes you're just stuck and frozen unable to continue. 
In the patch they seemed to have changed the UI within the game which is likely why this is now incompatible and causing issues.

**Comment by TheRealDjmr** [comment]
Updated - https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.6
