### ISSUE TITLE
BUG report：This mod makes texture load very slow

### ISSUE THREAD

**Issue by clark1091** [TheRealDjmr/BG3ImprovedUI#57]
Normally my game could load the texture just in few seconds even can't be noticed，but with this mod I have to wait for minutes or endure the low texture，hope it could be improved

Sorry for my bad English

**Comment by TheRealDjmr** [comment]
This mod doesn't change anything to do with texture generation, can you provide evidence (ideally video) to highlight what you mean?

**Comment by TheRealDjmr** [comment]
Closing due to not enough information
