### ISSUE TITLE
Character creation has dark urge and 8 nude humans

### ISSUE THREAD

**Issue by zuliwa** [TheRealDjmr/BG3ImprovedUI#65]
With this mod installed (even with it installed as my only mod) the character creation scene is a bugged void-like area with the dark urge character and eight nude humans, one of which is the player character.
The mod was installed on a completely fresh install of the game, and as mentioned is the only mod that has been installed

![Screenshot 2023-09-06 132447](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/11893054/40611aff-ff68-43a3-8c13-19a1e5906d88)

**Comment by TheRealDjmr** [comment]
This is clearly covered in the README and install instructions.

This has been added to your mod order, so you need story fix. If you don't add ImprovedUI to your mod order, story fix is no longer required for ImprovedUI (but can be required for other mods)
