### ISSUE TITLE
Feature Request: Togglable Versatile

### ISSUE THREAD

**Issue by drkekyll** [TheRealDjmr/BG3ImprovedUI#82]
Is it possible to have a button toggle one/two handed use for versatile weapons so you can use them one handed without a shield? I'm not entirely sure why anyone would want to for any reason other than aesthetics, but aesthetics are enough for me.

**Comment by TheRealDjmr** [comment]
Sounds like you want a button that "Locks" the option for offhand wielding/shields when using a versatile weapon, so that you can't equip anything into that slot?

**Comment by TheRealDjmr** [comment]
Or you want to force 1H usage without having to equip something in the offhand? That would most likely cause more problems than it solves with the damage reduction/confusion

**Comment by drkekyll** [comment]
The second thing. I want to force 1H usage without having to equip an off-hand. I figured a toggle near the auto dual wielding button that defaults to 2H usage of versatile weapons would be best if possible. That way you're unlikely to accidentally have it toggled on and wonder why you're doing less damage, though, in theory, the animation would be different. Alternatively, a toggle for shield visibility would accomplish the aesthetic goal.

**Comment by TheRealDjmr** [comment]
I have been mulling over this one for a while.

Both Shield visibility and weapon handling are outside of UI so I'm going to let this one go

It is possible to do funky things with weapons and shields outside the UI, see https://www.nexusmods.com/baldursgate3/mods/3013
