### ISSUE TITLE
[Bug] Action resource icons not visible

### ISSUE THREAD

**Issue by captainshrimps** [TheRealDjmr/BG3ImprovedUI#89]
![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/71992021/13944b32-3b30-45cf-a23e-81983405873e)

All the action resource icons with the exception of the cantrip icon are bugged and invisible as seen in the screenshot. I've confirmed it must be caused by ImprovedUI by loading the game with only ImprovedUI enabled and the bug was still there.

**Comment by Proxima-b** [comment]
I can confirm this is indeed happening to me

**Comment by TheRealDjmr** [comment]
Duplicate - https://github.com/TheRealDjmr/BG3ImprovedUI/issues/78
