### ISSUE TITLE
Reactions and spells icon

### ISSUE THREAD

**Issue by Pleureuse** [TheRealDjmr/BG3ImprovedUI#94]
![image](https://github.com/TheRealDjmr/BG3ImprovedUI/assets/126256967/0faa84db-ff4c-4615-92a4-8422aa31c6f5)

Seems there is a small oopsie somewhere ! :)

**Comment by TheRealDjmr** [comment]
This is Controller UI? Haven't seen that spell icon before

**Comment by Pleureuse** [comment]
Nah it's normal pc, only appeared after i updated to the new version of ImprovedUi

**Comment by TheRealDjmr** [comment]
Fixed in latest upload - https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.8
