### ISSUE TITLE
No more class icon on character creation/level up for modded classes

### ISSUE THREAD

**Issue by Mythalar** [TheRealDjmr/BG3ImprovedUI#97]
Hey there,

I cannot be certain of the timeframe but for some days I don't have icon anymore for the magus modded class (and arcanist, which is not supported). I guess it gets backs to the successives lately updates.

I always had the generic icon and not the shiny one for magus, but now the icons are just missing.
There is no issue with toolbar icons, only the class ones.

As of now I use the latest versions of IMprovedUI and assets (3.8.3)

Mod list linked because quite big ^^
[Public_Current 1.txt](https://github.com/TheRealDjmr/BG3ImprovedUI/files/12643761/Public_Current.1.txt)

**Comment by TheRealDjmr** [comment]
Have you updated ImprovedUI to 3.8

**Comment by Mythalar** [comment]
Yes, ImprovedUI and assets from [3.8 release](https://github.com/TheRealDjmr/BG3ImprovedUI/releases/tag/3.8)

**Comment by Mythalar** [comment]
Yes thought so since they are blank.
My mod list is attached to my first post because a tad long...

As for loose files I only have three texture mods (Younger Haslin, Younger Gale and Mature Astarion), and the No romance limit mod.
(will have to check at home)

**Comment by Mythalar** [comment]
Could check the loose files : the retexture ones + Smaller flutes + No romance limit + No Press Any Key Menu

**Comment by Mythalar** [comment]
I tried to reinstall ImprovedUI-366-3-7-1694295861 along with corresponding assets and the "generic" (same as first screen) icons are back for Arcanist and Magus (still not the actual magus mod icons).
Updating cause them to disappear.

**Comment by TheRealDjmr** [comment]
Over 100 mods are difficult to troubleshoot. Try a new save with just ImprovedUI, Arcanist and Magus. Then start adding mods until you get the issue. Mods that 

Arcanist doesn't have an icon it just uses the generic one.

An old version of Clerics can cause issues. Other than that I don't know any issues with the rest.

If a mod that's not dice and doesn't have custom icons show in BG3MM with "This mod overwrites base game files directly" it might be that one

**Comment by Mythalar** [comment]
So problem fixed which was a loose DataTemplates file in Game/GUI/Library.

I attach it to this message if of any use since I just cannot recall from what mod it comes from.
Thanks for your time !
[DataTemplates.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/12652881/DataTemplates.zip)
